FROM node:lts-bullseye-slim

RUN apt update \
    && apt install bc -y \
    && apt install -y procps \
    && apt install curl -y \
    && apt install inotify-tools -y \
    && apt install jo -y \
    && apt install jq -y \
    && apt install git -y \
    && apt install python3 make g++ -y \
    && rm -rf /var/cache/apk/* \
    && npm install --location=global npm -y \
    && npm install -g npm-check \
    && cd /usr/local/bin \
    && curl https://getmic.ro | bash

WORKDIR /Galaxy
COPY Next/package*.json ./
COPY Extensions /
RUN npm install