name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name:  Login in Docker Hub 
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Infra/DockerFile --tag mohammadmiras/galaxy:latest
 
      - name: Publish Image in Docker Hub
        run: |
             docker push mohammadmiras/galaxy:latest


